### ISSUE TITLE
🚨 [BUG Report] : Safari 환경에서 투표 현황을 볼 때 시간이 밀리는 문제

### ISSUE THREAD

**Issue by KUcodemaster** [ryuni-dev/meezzle#58]
## 🐞 Bug Description

<img width="463" alt="스크린샷 2023-03-30 오전 11 13 24" src="https://user-images.githubusercontent.com/78628241/228710369-dded1fb1-8b84-4802-ae07-a8cb9f37345c.png">

 - Safari 환경에서 투표 현황을 볼 때 시간이 밀리는 문제가 있음

## 🔎 To Reproduce
- (Mac) Safari로 투표 통계를 본다.

## 💡 Solution 
- 크로스브라우징 이슈에 대해 공부
- 아마도 CSS에 prefix를 붙이는 방식으로 해결이 가능할 듯

**Comment by ryuni-dev** [comment]
#60 해결 완료되어 이슈 종료합니다!
